export type ActionType = string 

export const UPDATE_QUESTIONS: ActionType = "UPDATE_QUESTIONS"
export const UPDATE_SUBJECT_NAME: ActionType = "UPDATE_SUBJECT_NAME"
export const UPDATE_CURRENT_PAGE_NUMBER: ActionType = "UPDATE_CURRENT_PAGE_NUMBER"
export const UPDATE_ATTEMPT_TREE: ActionType = "UPDATE_ATTEMPT_TREE"
export const UPDATE_ISMARKED: ActionType = "UPDATE_ISMARKED"
export const UPDATE_DOING_STATE: ActionType = "UPDATE_DOING_STATE"
export const UPDATE_COMP_SUB_PAGE: ActionType = "UPDATE_COMP_SUB_PAGE"
export const UPDATE_NO_OF_QUES_PER_PAGE: ActionType = "UPDATE_NO_OF_QUES_PER_PAGE"
export const INITIALIZE_ATTEMPT_TREE_AT: ActionType = "INITIALIZE_ATTEMPT_TREE_AT"
export const UPDATE_ATTEMPT_TREE_AT: ActionType = "UPDATE_ATTEMPT_TREE_AT"
export const UPDATE_ATTEMPT_TREE_AT_AND_MOVE: ActionType = "UPDATE_ATTEMPT_TREE_AT_AND_MOVE"
export const UPDATE_TOTAL_MARKS: ActionType = "UPDATE_TOTAL_MARKS"
export const UPDATE_TIME_REMAINING: ActionType = "UPDATE_TIME_REMAINING"
export const UPDATE_CONGRATS_POP_UP_STATE: ActionType = "UPDATE_CONGRATS_POP_UP_STATE"


